backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'topic'
    label: 'Topic'
    folder: 'content/topic'
    create: true
    slug: 'index'
    media_folder: '../../assets'
    public_folder: ''
    path: '{{courseType}}/{{title}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'uuid' }
      - label: "Course type"
        name: "courseType"
        widget: "select"
        options:
          - { label: "Lesson", value: "lesson" }
          - { label: "Course", value: "course" }
          - { label: "Vocabulary", value: "vocabulary" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Thumbnail", name: "thumbnail", widget: "image"}
      - { label: 'Summary', name: 'summary', widget: 'string' }
  - name: 'lesson'
    label: 'Lesson'
    folder: 'content/lesson'
    create: true
    slug: 'index'
    media_folder: '../../assets'
    public_folder: ''
    path: '{{courseType}}/{{title}}'
    fields:
      - { label: 'Id', name: 'id', widget: 'uuid' }
      - label: "Topic"
        name: "topicId"
        widget: "relation"
        collection: "topic"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "id"
      - label: "Course type"
        name: "courseType"
        widget: "select"
        options:
          - { label: "Lesson", value: "lesson" }
          - { label: "Course", value: "course" }
          - { label: "Vocabulary", value: "vocabulary" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

      